// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: greeting.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GreetingService_GetGenericGreeting_FullMethodName = "/proto.GreetingService/GetGenericGreeting"
	GreetingService_GetNamedGreeting_FullMethodName   = "/proto.GreetingService/GetNamedGreeting"
	GreetingService_GetVerboseGreeting_FullMethodName = "/proto.GreetingService/GetVerboseGreeting"
)

// GreetingServiceClient is the client API for GreetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetingServiceClient interface {
	GetGenericGreeting(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GreetingResponse, error)
	GetNamedGreeting(ctx context.Context, in *GetNamedGreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error)
	GetVerboseGreeting(ctx context.Context, in *GetVerboseGreetingRequest, opts ...grpc.CallOption) (*GetVerboseGreetingResponse, error)
}

type greetingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetingServiceClient(cc grpc.ClientConnInterface) GreetingServiceClient {
	return &greetingServiceClient{cc}
}

func (c *greetingServiceClient) GetGenericGreeting(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, GreetingService_GetGenericGreeting_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetingServiceClient) GetNamedGreeting(ctx context.Context, in *GetNamedGreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, GreetingService_GetNamedGreeting_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetingServiceClient) GetVerboseGreeting(ctx context.Context, in *GetVerboseGreetingRequest, opts ...grpc.CallOption) (*GetVerboseGreetingResponse, error) {
	out := new(GetVerboseGreetingResponse)
	err := c.cc.Invoke(ctx, GreetingService_GetVerboseGreeting_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetingServiceServer is the server API for GreetingService service.
// All implementations must embed UnimplementedGreetingServiceServer
// for forward compatibility
type GreetingServiceServer interface {
	GetGenericGreeting(context.Context, *emptypb.Empty) (*GreetingResponse, error)
	GetNamedGreeting(context.Context, *GetNamedGreetingRequest) (*GreetingResponse, error)
	GetVerboseGreeting(context.Context, *GetVerboseGreetingRequest) (*GetVerboseGreetingResponse, error)
	mustEmbedUnimplementedGreetingServiceServer()
}

// UnimplementedGreetingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGreetingServiceServer struct {
}

func (UnimplementedGreetingServiceServer) GetGenericGreeting(context.Context, *emptypb.Empty) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenericGreeting not implemented")
}
func (UnimplementedGreetingServiceServer) GetNamedGreeting(context.Context, *GetNamedGreetingRequest) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamedGreeting not implemented")
}
func (UnimplementedGreetingServiceServer) GetVerboseGreeting(context.Context, *GetVerboseGreetingRequest) (*GetVerboseGreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerboseGreeting not implemented")
}
func (UnimplementedGreetingServiceServer) mustEmbedUnimplementedGreetingServiceServer() {}

// UnsafeGreetingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetingServiceServer will
// result in compilation errors.
type UnsafeGreetingServiceServer interface {
	mustEmbedUnimplementedGreetingServiceServer()
}

func RegisterGreetingServiceServer(s grpc.ServiceRegistrar, srv GreetingServiceServer) {
	s.RegisterService(&GreetingService_ServiceDesc, srv)
}

func _GreetingService_GetGenericGreeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingServiceServer).GetGenericGreeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetingService_GetGenericGreeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingServiceServer).GetGenericGreeting(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetingService_GetNamedGreeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamedGreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingServiceServer).GetNamedGreeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetingService_GetNamedGreeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingServiceServer).GetNamedGreeting(ctx, req.(*GetNamedGreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetingService_GetVerboseGreeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerboseGreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingServiceServer).GetVerboseGreeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetingService_GetVerboseGreeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingServiceServer).GetVerboseGreeting(ctx, req.(*GetVerboseGreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreetingService_ServiceDesc is the grpc.ServiceDesc for GreetingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GreetingService",
	HandlerType: (*GreetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGenericGreeting",
			Handler:    _GreetingService_GetGenericGreeting_Handler,
		},
		{
			MethodName: "GetNamedGreeting",
			Handler:    _GreetingService_GetNamedGreeting_Handler,
		},
		{
			MethodName: "GetVerboseGreeting",
			Handler:    _GreetingService_GetVerboseGreeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeting.proto",
}
